export const GET_ALBUMS = "GET_ALBUMS";
export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILURE = "GET_ALBUMS_FAILURE";
export const SUBMIT_NOTE = "SUBMIT_NOTE";
export const SUBMIT_NOTE_SUCCESS = "SUBMIT_NOTE_SUCCESS";
export const SUBMIT_NOTE_FAILURE = "SUBMIT_NOTE_FAILURE";
